CREATE TABLE SPR_REPLY
(
	RNO NUMBER(10),
	BNO NUMBER(10),
	REPLY VARCHAR2(1000),
	REPLIER VARCHAR2(500),
	REPLYDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	CONSTRAINT PK_SPR_REPLY PRIMARY KEY(RNO),
	CONSTRAINT FK_SPR_REPLY_BOARD FOREIGN KEY(BNO)
		REFERENCES SPR_BOARD(BNO)
);

INSERT INTO SPR_REPLY(RNO, BNO, REPLY, REPLIER)
SELECT SEQ_REPLY.NEXTVAL, BNO, REPLY, REPLIER FROM SPR_REPLY WHERE BNO = 1400;

SELECT * FROM SPR_REPLY ORDER BY RNO;

SELECT RNO, BNO, REPLY, REPLIER, REPLYDATE, UPDATEDATE
FROM
(
	SELECT /*+ INDEX_DESC(SPR_REPLY, PK_SPR_REPLY) */ ROWNUM RN, RNO, BNO, REPLY, REPLIER, REPLYDATE, UPDATEDATE
	FROM SPR_REPLY
	WHERE BNO = 1400 AND
	ROWNUM <= 10
)
WHERE RN > 0;