CREATE SEQUENCE SEQ_BOARD;

-- TBL_BOARD는 JSP 강의에서 썼던 이름이므로 SPR_BOARD라고 명명

CREATE TABLE SPR_BOARD
(
	BNO NUMBER(10) PRIMARY KEY,
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

INSERT INTO SPR_BOARD
(BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE)
VALUES(SEQ_BOARD.NEXTVAL, '테스트 제목', '테스트 내용', 'user01', SYSDATE, SYSDATE);

INSERT INTO SPR_BOARD
(BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE)
VALUES(SEQ_BOARD.NEXTVAL, '테스트 제목', '테스트 내용', 'user01', SYSDATE, SYSDATE);

-- 더미데이터 잔뜩 넣기
INSERT INTO SPR_BOARD
(BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE)
SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE FROM SPR_BOARD;

-- 힌트 사용
SELECT /*+INDEX_DESC(SPR_BOARD, SYS_C007122)*/* FROM SPR_BOARD;
SELECT COUNT(1) FROM SPR_BOARD;
